#pragma once

#include <types.h>

/*Standard traps*/
#define RV_TRAP_INSTR_ADDR_MISALIGNED 0
#define RV_TRAP_INSTR_ACCESS_FAULT 1
#define RV_TRAP_ILLEGAL_INSTR 2
#define RV_TRAP_BREAKPOINT 3
#define RV_TRAP_LO_ADDRESS_MISALIGNED 4
#define RV_TRAP_LO_ACCESS_FAULT 5
#define RV_TRAP_ST_ADDRESS_MISALIGNED 6
#define RV_TRAP_ST_ACCESS_FAULT 7
#define RV_TRAP_ECALL_FROM_UMODE 8
#define RV_TRAP_ECALL_FROM_SMODE 9
#define RV_TRAP_ECALL_FROM_MMODE 11
#define RV_TRAP_INSTR_PAGE_FAULT 12
#define RV_TRAP_LO_PAGE_FAULT 13
#define RV_TRAP_ST_PAGE_FAULT 15
#define RV_TRAP_SOFTWARE_CHECK 18
#define RV_TRAP_HARDWARE_ERROR 19

#define RV_INTERRUPT_BIT ((uint64_t)1 << 63)
